permalink: pretty
sass:
    sass_dir: _sass
    style: :compressed
prose:
  ignore: [
    "_config.yml",
    ".gitignore",
    "blog.rss",
    "Gemfile",
    "Gemfile.lock",
    "index.html",
    "LICENCE.md",
    "links.jsonp",
    "manifest.appcache",
    "README.md",
    "site.js",
    "_includes",
    "_layouts",
    "_site",
    "_sass",
    "css",
    "js",
    "stylesheets",
    "vendor"
    ]
  media: 'media'
  metadata:
    _posts/faqs:
      - name: "category"
        field:
          element: "hidden"
          value: "faq"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "faqtype"
        field:
          element: "select"
          label: "FAQ Section"
          options:
            - name: Know Your Rights
              value: kyr
            - name: Post Release
              value: post-release
            - name: Jail Support
              value: jail-support
            - name: Donate
              value: donate
    _posts/resources:
      - name: "category"
        field:
          element: "hidden"
          value: "resources"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "resourcetype"
        field:
          element: "select"
          label: "FAQ Section"
          options:
            - name: Know Your Rights
              value: kyr
            - name: Post Release
              value: post-release
            - name: Jail Support
              value: jail-support
            - name: Donate
              value: donate
    _posts/updates:
      - name: "category"
        field:
          element: "hidden"
          value: "updates"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "resourcetype"
        field:
          element: "checkbox"
          label: "Is an Alert"
